### PR TITLE
Add pyproject.toml for Custom Node Registry

### PR DESCRIPTION
**Pull request by haohaocreates**
We are building a global registry for custom nodes (similar to PyPI). The registry makes using custom nodes more reliable by reserving globally unique names for each custom node, and supporting semantic versioning.

Here’s some [more information](https://www.comfydocs.org/registry/overview#introduction) on the registry.

Action Required:

- [x] Go to the [registry](https://www.comfyregistry.org/). Login and create a publisher id. Comment it here and we will update the PR (or just merge it and change it yourself).
- [x] Write a short the description.
- [x] Merge the separate Github Actions PR and run the workflow.
If you want to publish the node manually, [install the cli](https://www.comfydocs.org/comfy-cli/getting-started#install-cli) and run `comfy node publish`

Please message me on [Discord](https://discord.com/invite/comfycontrib) if you have any questions!

### CODE REVIEW

**Comment by traugdor** [comment]
Can you go into more detail what this is for, why it is necessary, and how it is better than the current setup with have with the ComfyUI Manager?

**Comment by traugdor** [comment]
@haohaocreates please respond:

Can you go into more detail what this is for, why it is necessary, and how it is better than the current setup with have with the ComfyUI Manager?

**Comment by haohaocreates** [comment]
Yes! Sorry for the long wait, I've just been travelling over this last week!

So the registry is a project we are working with dr.lt.data and comfyanon
and it's kind of like npm/pypi but for custom nodes. It'll eventually be
integrated as a backend for the UI-manager (people will be able to
install/update nodes through both the manager and registry). Custom nodes
will go through a verification process in this system, and once verified,
they'll be published to users.

The main benefits of the registry is that it enables node authors to
- publish nodes to publish by version (we're using semver); this way people
can reproduce workflows, users can safely update nodes knowing that their
workflows will or won't break
- automate testing against new commits to the comfy repo as well as
existing workflows (we've set up a CI/CD dashboard) to see if new node
updates will break workflows your users have

Let me know if there are other questions! We also have a docs page as well!
https://www.comfydocs.org/registry/overview

Best,

**Review by traugdor — APPROVED** [review]
Approved. Will add PublisherID later.

**Pull request merged**
